# Generated by Django 3.0.5 on 2020-04-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文集名称')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'Anthology',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('love_num', models.IntegerField(default=0, verbose_name='点赞量')),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Anthology', verbose_name='文集')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
