# Generated by Django 3.0.5 on 2020-04-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='上次编辑'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
