# Generated by Django 3.0.5 on 2020-04-28 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_edit',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 23, 34, 35, 700585), verbose_name='上次编辑'),
        ),
    ]
