# Generated by Django 3.0.5 on 2020-04-29 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200428_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 8, 55, 25, 362020), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='上次编辑'),
        ),
    ]
