# Generated by Django 3.0.3 on 2020-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='User/<django.db.models.fields.AutoField>/%Y%m%d/', verbose_name='头像'),
        ),
    ]
