# Generated by Django 3.0.5 on 2020-04-12 11:22

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200412_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, storage=system.storage.ImageStorage(), upload_to='up_load/'),
        ),
    ]
