# Generated by Django 3.0.5 on 2020-04-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200412_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='up_load/'),
        ),
    ]
